default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: test123
  socket: /var/run/mysqld/mysqld.sock
development:
  <<: *default
  database: your_story_development
test:
  <<: *default
  database: your_story_test
  username: root
  password: test123
production:
  <<: *default
  database: your_story_production
  username: root
  password: test123
